query problemsetRandomFilteredQuestion(
  $categorySlug: String!
  $filters: QuestionListFilterInput
) {
  problemsetRandomFilteredQuestion(
    categorySlug: $categorySlug
    filters: $filters
  )
}
